spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: postgres
    password: w3e4r5t6y7

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: 8081